spring:
  datasource:
    hikari:
      username: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/boarddb?useSSL=true&serverTimezone=UTC
      password: '1234'
  thymeleaf:
    prefix: file:src/main/resources/templates/
    cache: 'false'
  mvc:
    servlet:
      load-on-startup: '1'
  devtools:
    restart:
      enabled: 'false'
    livereload:
      enabled: 'true'
mybatis:
  configuration:
    map-underscore-to-camel-case: 'true'
